apiVersion: apps/v1
kind: Deployment
metadata:
  name: yasn-cloud-config
spec:
  selector:
    matchLabels:
      app: yasn-cloud-config
  replicas: 1 #Pods quantity for one deployment
  template:
    metadata:
      labels:
        app: yasn-cloud-config
        visualize: "true"
    spec:
      containers:
      - name: yasn-cloud-config
        image: regyl/yasn-cloud-config #Docker image
        ports:
        - containerPort: 8760
---
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: yasn-cloud-config-service
spec:
  selector:
    app: yasn-cloud-config
  ports:
  - name: http
    protocol: TCP
    port: 8760
    targetPort: 8760
  type: ClusterIP
