apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-checker
spec:
  selector:
    matchLabels:
      app: currency-checker
  replicas: 1 #Pods quantity for one deployment
  template:
    metadata:
      labels:
        app: currency-checker
        visualize: "true"
    spec:
      containers:
      - name: currency-checker
        image: regyl/currency-checker #Docker image
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: currency-checker-service
spec:
  selector:
    app: currency-checker
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
